service: ec-compute

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: us-east-1

  iamRoleStatements:
    - Effect: Allow
      Action:
        - "execute-api:Invoke"
      Resource: "arn:aws:execute-api:${self:provider.region}:*:*"
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: "arn:aws:lambda:${self:provider.region}:*:function:*"

functions:
    my-lambda:
        handler: lambda/index.handler
        timeout: 70

package:
  exclude:
    - node_modules/**
    - venv/**

plugins:
  - serverless-python-requirements